### PR TITLE
Fix reproducible builds, remove user generated files, binaries and add a .gitignore

### PR DESCRIPTION
**Pull request by handsomematt**
I had a lot of issues building this and getting it to work, I've made a few changes to the overall project structure as well as removed a lot of your user preference files for Visual Studio that forced mine to Russian and other misc errors.

I've removed the binaries from the project directory as these should be built and released on the releases section of GitHub, I've also changed the output directory to `bin` and x86, x64 now build to their respective folders: `bin` and `bin64` to please GW2. I have also moved `pck` to `bin` so you can just copy and paste the `bin` folder directly into your GW2 folder, it was not clear that `pck` had to be inside a `d912pxy` folder in the root directory.

I moved third party libraries to the `thirdparty` folder.

Updated LICENSE to the year, and split `README.md` into that and `README.ru.md`.

And finally I added a `.gitignore` so junk files aren't committed.

### CODE REVIEW

**Comment by megai2** [comment]
Will look it up, but need to get familiar with all github/git/opensource practices.

**Comment by worksasintended** [comment]
What @handsomematt did is a quite necessary and a first step for us to proofread your programming. If this is legit I highly thank you!
Just a rule of thumb: Everything in the repo is just stuff everybody needs. So no personal development space files or binaries.

**Comment by megai2** [comment]
> 
> 
> Ah another note is I removed the .bat files, since the `bin` folder should represent exactly what you would copy to the gw2 folder. Binaries build to: `/bin/bin64/d3d9.dll` for instance.

1. Some folks have a problem that game use root directory to load dll's, not bin64
2. Fact that there is 2 files to copy and also additional build versions, can make ppl make mess with it.
2.* Especially when removing it, as there is manual look/check/delete sequence instead of stupidly running .bat file
3. Some want their modded d3d9.dll to stay after all, so install/remove script makes backups.

I think using somekind of .bat "sources" will be a good solution, same with .hlsl files, as for now they not linked to project properly.

**Comment by handsomematt** [comment]
So in regards to 2, I think when a release is published there should be different zip files released for each configuration:

* d912pxy-debug.zip
* d912pxy-release.zip
* etc..

with the contents being the contents of the `bin` folder like so:

* bin64
* * d3d9.dll
* d912pxy
* * pck
* * shaders

And the general idea would to be just drag and drop in your Guild Wars 2 folder. Does this sound okay?

**Pull request merged**
